/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/assignments': typeof AssignmentsRoute
  '/maintenance': typeof MaintenanceRoute
  '/transfers': typeof TransfersRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/maintenance': typeof MaintenanceRoute
  '/transfers': typeof TransfersRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets': typeof AssetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/assignments': typeof AssignmentsRoute
  '/maintenance': typeof MaintenanceRoute
  '/transfers': typeof TransfersRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets/': typeof AssetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/assignments'
    | '/maintenance'
    | '/transfers'
    | '/assets/$id'
    | '/assets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/maintenance'
    | '/transfers'
    | '/assets/$id'
    | '/assets'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/assignments'
    | '/maintenance'
    | '/transfers'
    | '/assets/$id'
    | '/assets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  AssignmentsRoute: typeof AssignmentsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  TransfersRoute: typeof TransfersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof AssetsRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsIdRoute: typeof AssetsIdRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsIdRoute: AssetsIdRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  AssignmentsRoute: AssignmentsRoute,
  MaintenanceRoute: MaintenanceRoute,
  TransfersRoute: TransfersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
